version: "3.3"

services:

  postgres:
    build:
      context: 
        docker/postgres
    image:
      local/postgres_miguilim
    container_name: 
      local_bd_miguilim
    ports:
      - "5006:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    networks:
      - nw_miguilim_local

  dspace:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image:
      local/dspace_miguilim
    environment:
      - TZ=America/Sao_Paulo
      - CONFIG_FILE=docker.cfg
      - DEV_MODE=true
      - CONTEXT_NAME=miguilim
    container_name: 
      local_dspace_miguilim
    ports:
      - "7006:8080"
    tty: 
      true
    volumes:
      - localmavenrepo:/root/.m2/repository
      - localinstallfolder:/dspace
    networks:
      - nw_miguilim_local

networks:
  nw_miguilim_local:
    driver: bridge

volumes:
  localmavenrepo:
    driver: local
  localinstallfolder:
    driver: local