name: Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # - name: Set Up JDK 8
      #  uses: actions/setup-java@v2
      #  with:
      #   java-version: '8'
      #   distribution: 'adopt'
      #   cache: 'maven'

      - name: Set Up JDK 8 and Maven 3.6.3
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '8'
          maven-version: '3.6.3'
      
      - name: Compile
        run: mvn clean package
      
      - name: Deploy Up
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Down Down
        run: docker-compose -f "docker-compose.yml" down

     