name: Deploy with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Compile
        run: mvn clean package
      
      - name: Deploy Up
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Down Down
        run: docker-compose -f "docker-compose.yml" down

     