name: Deploy Via VPN

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run hello-world

      
